//! ADIF (ADI) rendering, kept in sync with `web/src/lib/qso/adif.ts`, and reading.

use std::collections::HashMap;

use crate::{
    band::band_for_frequency,
    qso::{Qsl, QsoPayload},
    stations::Station,
};

/// The values a station provides wherever a QSO leaves them empty.
#[derive(Debug, Default, PartialEq, Eq)]
struct StationDefaults {
    station_callsign: Option<String>,
    location: Option<String>,
    pota_ref: Option<String>,
    my_jcx: Option<String>,
}

impl StationDefaults {
    /// Keep in sync with `stationDefaults` in `web/src/lib/qso/station.ts`.
    fn of(station: Option<&Station>) -> Self {
        let Some(s) = station else {
            return Self::default();
        };
        let present = |v: &str| Some(v.trim()).filter(|v| !v.is_empty()).map(str::to_string);
        Self {
            station_callsign: present(&s.callsign).map(|c| c.to_uppercase()),
            location: present(&s.city),
            pota_ref: present(&s.pota).map(|p| p.to_uppercase()),
            my_jcx: present(&s.cnty),
        }
    }
}

fn field(out: &mut String, name: &str, value: Option<&str>) {
    if let Some(value) = value.filter(|v| !v.is_empty()) {
        out.push_str(&format!("<{name}:{}>{value} ", value.chars().count()));
    }
}

/// Formats Hz as an ADIF FREQ value in MHz without trailing zeros.
pub fn frequency(hz: u64) -> String {
    let s = format!("{}.{:06}", hz / 1_000_000, hz % 1_000_000);
    s.trim_end_matches('0').trim_end_matches('.').to_string()
}

/// Renders one QSO as an ADI record terminated by `<EOR>`; the station fills in what the QSO left
/// to it.
pub fn record(qso: &QsoPayload, station: Option<&Station>) -> String {
    let defaults = StationDefaults::of(station);
    let mut out = String::new();
    let date = qso.time_on.format("%Y%m%d").to_string();
    let time = qso.time_on.format("%H%M%S").to_string();
    let freq = frequency(qso.frequency);
    let pota = qso.pota_ref.as_deref().or(defaults.pota_ref.as_deref());
    let location = Some(qso.location.as_str())
        .filter(|l| !l.is_empty())
        .or(defaults.location.as_deref());

    field(&mut out, "CALL", Some(&qso.call));
    field(&mut out, "QSO_DATE", Some(&date));
    field(&mut out, "TIME_ON", Some(&time));
    field(&mut out, "FREQ", Some(&freq));
    field(&mut out, "BAND", band_for_frequency(qso.frequency));
    field(&mut out, "MODE", Some(&qso.mode));
    field(&mut out, "RST_SENT", Some(&qso.rst_sent));
    field(&mut out, "RST_RCVD", Some(&qso.rst_rcvd));
    // Requested: we owe a card. One way: we send none and one is on its way to us.
    let (qsl_sent, qsl_rcvd) = match qso.qsl {
        Qsl::None => (None, None),
        Qsl::Requested => (Some("R"), None),
        Qsl::OneWay => (Some("N"), Some("R")),
    };
    field(&mut out, "QSL_SENT", qsl_sent);
    field(&mut out, "QSL_RCVD", qsl_rcvd);
    field(&mut out, "CNTY", qso.jcx.as_deref());
    field(&mut out, "OPERATOR", qso.operator.as_deref());
    field(
        &mut out,
        "STATION_CALLSIGN",
        qso.station_callsign
            .as_deref()
            .or(defaults.station_callsign.as_deref())
            .or(qso.operator.as_deref()),
    );
    field(&mut out, "MY_CITY", location);
    field(
        &mut out,
        "APP_SPEECHTOQSO_MY_JCX",
        qso.my_jcx.as_deref().or(defaults.my_jcx.as_deref()),
    );
    field(&mut out, "MY_SIG", pota.map(|_| "POTA"));
    field(&mut out, "MY_SIG_INFO", pota);
    field(&mut out, "MY_POTA_REF", pota);
    out.push_str("<EOR>");
    out
}

/// Header for a freshly created ADIF file.
pub fn header() -> String {
    let mut out = String::from("Generated by speech-to-qso-server\n");
    field(&mut out, "ADIF_VER", Some("3.1.4"));
    field(&mut out, "PROGRAMID", Some("speech-to-qso"));
    out.push_str("<EOH>\n");
    out
}

/// Reads the records of an ADI file, with upper-case field names. Field lengths count characters,
/// like `field` and Wavelog's export write them.
pub fn read_records(text: &str) -> Vec<HashMap<String, String>> {
    let mut records = Vec::new();
    let mut fields = HashMap::new();
    let mut rest = text;
    while let Some(start) = rest.find('<') {
        let Some(length) = rest[start..].find('>') else {
            break;
        };
        let tag = &rest[start + 1..start + length];
        rest = &rest[start + length + 1..];
        let mut parts = tag.split(':');
        let name = parts.next().unwrap_or_default().trim().to_ascii_uppercase();
        match name.as_str() {
            "EOH" => fields.clear(),
            "EOR" => records.push(std::mem::take(&mut fields)),
            _ => {
                let Some(length) = parts.next().and_then(|l| l.trim().parse::<usize>().ok()) else {
                    continue;
                };
                let end = rest.char_indices().nth(length).map_or(rest.len(), |(i, _)| i);
                fields.insert(name, rest[..end].to_string());
                rest = &rest[end..];
            }
        }
    }
    records
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::qso::tests::sample;

    #[test]
    fn renders_the_same_record_as_the_web_client() {
        // Identical to the expectation in web/src/lib/qso/adif.test.ts.
        assert_eq!(
            record(&sample(), None),
            "<CALL:6>JL1HIS <QSO_DATE:8>20261003 <TIME_ON:6>040506 <FREQ:6>432.94 <BAND:4>70cm \
             <MODE:2>FM <RST_SENT:2>59 <RST_RCVD:2>57 <QSL_SENT:1>R <CNTY:6>100101 \
             <OPERATOR:6>JJ1ABC <STATION_CALLSIGN:6>JJ1ABC <MY_CITY:6>Minato <MY_SIG:4>POTA <MY_SIG_INFO:7>JP-0001 <MY_POTA_REF:7>JP-0001 <EOR>"
        );
    }

    #[test]
    fn renders_a_one_way_card_as_nothing_to_send_and_a_card_to_receive() {
        let mut qso = sample();
        qso.qsl = Qsl::OneWay;
        // Identical to the expectation in web/src/lib/qso/adif.test.ts.
        assert!(record(&qso, None).contains("<RST_RCVD:2>57 <QSL_SENT:1>N <QSL_RCVD:1>R <CNTY:6>100101 "));
    }

    #[test]
    fn uses_the_station_callsign_when_given() {
        let mut qso = sample();
        qso.station_callsign = Some("JJ1ABC/1".into());
        // Identical to the expectation in web/src/lib/qso/adif.test.ts.
        assert!(record(&qso, None).contains("<OPERATOR:6>JJ1ABC <STATION_CALLSIGN:8>JJ1ABC/1 "));
    }

    #[test]
    fn leaves_the_operator_out_when_wavelog_fills_it_in() {
        let mut qso = sample();
        qso.operator = None;
        qso.station_callsign = Some("JJ1ABC/1".into());
        // Identical to the expectation in web/src/lib/qso/adif.test.ts.
        assert!(record(&qso, None).contains("<CNTY:6>100101 <STATION_CALLSIGN:8>JJ1ABC/1 <MY_CITY:6>"));
    }

    #[test]
    fn fills_in_what_the_qso_left_to_its_station() {
        let station = Station {
            id: "park".into(),
            wavelog_id: Some(1),
            name: "Park".into(),
            callsign: "JJ1ABC/1".into(),
            gridsquare: String::new(),
            city: "Minato".into(),
            state: String::new(),
            cnty: "100101".into(),
            pota: "JP-0001".into(),
            sota: String::new(),
            wwff: String::new(),
            iota: String::new(),
            sig: String::new(),
            sig_info: String::new(),
            power: None,
            active: true,
        };
        let mut qso = sample();
        qso.operator = None;
        qso.location = String::new();
        qso.pota_ref = None;
        // Identical to the expectation in web/src/lib/qso/adif.test.ts.
        assert!(record(&qso, Some(&station)).contains(
            "<STATION_CALLSIGN:8>JJ1ABC/1 <MY_CITY:6>Minato <APP_SPEECHTOQSO_MY_JCX:6>100101 \
             <MY_SIG:4>POTA <MY_SIG_INFO:7>JP-0001 <MY_POTA_REF:7>JP-0001 <EOR>"
        ));
        // The QSO's own values win.
        qso.location = "Shiba".into();
        assert!(record(&qso, Some(&station)).contains("<MY_CITY:5>Shiba "));
    }

    #[test]
    fn omits_empty_fields_and_counts_characters() {
        let mut qso = sample();
        qso.jcx = None;
        qso.qsl = Qsl::None;
        qso.pota_ref = None;
        qso.location = "東京都港区".into();
        let adif = record(&qso, None);
        assert!(!adif.contains("QSL_"));
        assert!(!adif.contains("CNTY"));
        assert!(!adif.contains("MY_SIG"));
        assert!(adif.contains("<MY_CITY:5>東京都港区 "));
    }

    #[test]
    fn reads_records_after_the_header() {
        let text = "Wavelog ADIF export
<ADIF_VER:5>3.1.7
<PROGRAMID:7>Wavelog
<EOH>

                    <CALL:6>JL1HIS
<QTH:5>東京都港区
<qsl_sent:1>Y
<EOR>
                    <CALL:6>JL1HIS <APP_X:3:S>a<b <EOR>";
        let records = read_records(text);
        assert_eq!(records.len(), 2);
        assert_eq!(records[0]["CALL"], "JL1HIS");
        assert_eq!(records[0]["QTH"], "東京都港区");
        assert_eq!(records[0]["QSL_SENT"], "Y");
        assert!(!records[0].contains_key("ADIF_VER"));
        assert_eq!(records[1]["APP_X"], "a<b");
    }

    #[test]
    fn reads_back_what_it_writes() {
        let records = read_records(&format!("{}{}", header(), record(&sample(), None)));
        assert_eq!(records.len(), 1);
        assert_eq!(records[0]["CALL"], "JL1HIS");
        assert_eq!(records[0]["MY_POTA_REF"], "JP-0001");
    }

    #[test]
    fn formats_frequencies() {
        assert_eq!(frequency(432_940_000), "432.94");
        assert_eq!(frequency(7_000_000), "7");
        assert_eq!(frequency(7_123_456), "7.123456");
    }
}
