//! ADIF (ADI) rendering. Keep in sync with `web/src/lib/qso/adif.ts`.

use crate::{band::band_for_frequency, qso::QsoPayload};

fn field(out: &mut String, name: &str, value: Option<&str>) {
    if let Some(value) = value.filter(|v| !v.is_empty()) {
        out.push_str(&format!("<{name}:{}>{value} ", value.chars().count()));
    }
}

/// Formats Hz as an ADIF FREQ value in MHz without trailing zeros.
pub fn frequency(hz: u64) -> String {
    let s = format!("{}.{:06}", hz / 1_000_000, hz % 1_000_000);
    s.trim_end_matches('0').trim_end_matches('.').to_string()
}

/// Renders one QSO as an ADI record terminated by `<EOR>`.
pub fn record(qso: &QsoPayload) -> String {
    let mut out = String::new();
    let date = qso.time_on.format("%Y%m%d").to_string();
    let time = qso.time_on.format("%H%M%S").to_string();
    let freq = frequency(qso.frequency);
    let comment = qso.jcx.as_ref().map(|jcx| format!("JCX {jcx}"));
    let pota = qso.pota_ref.as_deref();

    field(&mut out, "CALL", Some(&qso.call));
    field(&mut out, "QSO_DATE", Some(&date));
    field(&mut out, "TIME_ON", Some(&time));
    field(&mut out, "FREQ", Some(&freq));
    field(&mut out, "BAND", band_for_frequency(qso.frequency));
    field(&mut out, "MODE", Some(&qso.mode));
    field(&mut out, "RST_SENT", Some(&qso.rst_sent));
    field(&mut out, "RST_RCVD", Some(&qso.rst_rcvd));
    field(&mut out, "QSL_SENT", qso.qsl_requested.then_some("R"));
    field(&mut out, "COMMENT", comment.as_deref());
    field(&mut out, "APP_SPEECHTOQSO_JCX", qso.jcx.as_deref());
    field(&mut out, "OPERATOR", Some(&qso.operator));
    field(&mut out, "STATION_CALLSIGN", Some(&qso.operator));
    field(&mut out, "MY_CITY", Some(&qso.location));
    field(&mut out, "APP_SPEECHTOQSO_MY_JCX", qso.my_jcx.as_deref());
    field(&mut out, "MY_SIG", pota.map(|_| "POTA"));
    field(&mut out, "MY_SIG_INFO", pota);
    field(&mut out, "MY_POTA_REF", pota);
    out.push_str("<EOR>");
    out
}

/// Header for a freshly created ADIF file.
pub fn header() -> String {
    let mut out = String::from("Generated by speech-to-qso-server\n");
    field(&mut out, "ADIF_VER", Some("3.1.4"));
    field(&mut out, "PROGRAMID", Some("speech-to-qso"));
    out.push_str("<EOH>\n");
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::qso::tests::sample;

    #[test]
    fn renders_the_same_record_as_the_web_client() {
        // Identical to the expectation in web/src/lib/qso/adif.test.ts.
        assert_eq!(
            record(&sample()),
            "<CALL:6>JL1HIS <QSO_DATE:8>20261003 <TIME_ON:6>040506 <FREQ:6>432.94 <BAND:4>70cm \
             <MODE:2>FM <RST_SENT:2>59 <RST_RCVD:2>57 <QSL_SENT:1>R <COMMENT:10>JCX 100101 \
             <APP_SPEECHTOQSO_JCX:6>100101 <OPERATOR:6>JJ1ABC <STATION_CALLSIGN:6>JJ1ABC \
             <MY_CITY:6>Minato <MY_SIG:4>POTA <MY_SIG_INFO:7>JP-0001 <MY_POTA_REF:7>JP-0001 <EOR>"
        );
    }

    #[test]
    fn omits_empty_fields_and_counts_characters() {
        let mut qso = sample();
        qso.jcx = None;
        qso.qsl_requested = false;
        qso.pota_ref = None;
        qso.location = "東京都港区".into();
        let adif = record(&qso);
        assert!(!adif.contains("QSL_SENT"));
        assert!(!adif.contains("JCX"));
        assert!(!adif.contains("MY_SIG"));
        assert!(adif.contains("<MY_CITY:5>東京都港区 "));
    }

    #[test]
    fn formats_frequencies() {
        assert_eq!(frequency(432_940_000), "432.94");
        assert_eq!(frequency(7_000_000), "7");
        assert_eq!(frequency(7_123_456), "7.123456");
    }
}
