//! Append-only local QSO log.
//!
//! `qsos.jsonl` is an event log used to rebuild the de-duplication state on startup;
//! `log.adi` is a plain ADIF log that any logging program can import.

use std::{
    collections::HashMap,
    io,
    path::{Path, PathBuf},
};

use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use tokio::{fs, io::AsyncWriteExt};

use crate::{adif, qso::QsoPayload};

#[derive(Debug, Serialize, Deserialize)]
#[serde(tag = "event", rename_all = "snake_case")]
enum Event {
    Received { at: DateTime<Utc>, qso: Box<QsoPayload> },
    Forwarded { at: DateTime<Utc>, id: String },
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Entry {
    /// Whether the QSO has been uploaded to Wavelog.
    pub forwarded: bool,
}

#[derive(Debug)]
pub struct Store {
    events_path: PathBuf,
    adif_path: PathBuf,
    entries: HashMap<String, Entry>,
}

impl Store {
    pub async fn open(dir: &Path) -> io::Result<Self> {
        fs::create_dir_all(dir).await?;
        let events_path = dir.join("qsos.jsonl");
        let adif_path = dir.join("log.adi");

        let mut entries = HashMap::new();
        match fs::read_to_string(&events_path).await {
            Ok(text) => {
                for (n, line) in text.lines().enumerate().filter(|(_, l)| !l.trim().is_empty()) {
                    match serde_json::from_str(line) {
                        Ok(Event::Received { qso, .. }) => {
                            entries.entry(qso.id).or_insert(Entry { forwarded: false });
                        }
                        Ok(Event::Forwarded { id, .. }) => {
                            entries.insert(id, Entry { forwarded: true });
                        }
                        Err(e) => tracing::warn!("{}:{}: skipping bad line: {e}", events_path.display(), n + 1),
                    }
                }
            }
            Err(e) if e.kind() == io::ErrorKind::NotFound => {}
            Err(e) => return Err(e),
        }

        Ok(Self {
            events_path,
            adif_path,
            entries,
        })
    }

    pub fn get(&self, id: &str) -> Option<Entry> {
        self.entries.get(id).copied()
    }

    pub fn len(&self) -> usize {
        self.entries.len()
    }

    pub fn is_empty(&self) -> bool {
        self.entries.is_empty()
    }

    async fn append(path: &Path, text: &str) -> io::Result<()> {
        let mut file = fs::OpenOptions::new().create(true).append(true).open(path).await?;
        file.write_all(text.as_bytes()).await?;
        file.sync_data().await
    }

    async fn append_event(&self, event: &Event) -> io::Result<()> {
        let mut line = serde_json::to_string(event).map_err(io::Error::other)?;
        line.push('\n');
        Self::append(&self.events_path, &line).await
    }

    /// Records a newly received QSO in both logs.
    pub async fn record_received(&mut self, qso: &QsoPayload) -> io::Result<()> {
        self.append_event(&Event::Received {
            at: Utc::now(),
            qso: Box::new(qso.clone()),
        })
        .await?;
        let mut text = String::new();
        if fs::metadata(&self.adif_path).await.is_err() {
            text.push_str(&adif::header());
        }
        text.push_str(&adif::record(qso));
        text.push('\n');
        Self::append(&self.adif_path, &text).await?;
        self.entries.insert(qso.id.clone(), Entry { forwarded: false });
        Ok(())
    }

    /// Records that a QSO has been uploaded to Wavelog.
    pub async fn record_forwarded(&mut self, id: &str) -> io::Result<()> {
        self.append_event(&Event::Forwarded {
            at: Utc::now(),
            id: id.to_string(),
        })
        .await?;
        self.entries.insert(id.to_string(), Entry { forwarded: true });
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::qso::tests::sample;

    #[tokio::test]
    async fn persists_and_reloads_state() {
        let dir = tempfile::tempdir().unwrap();
        let mut store = Store::open(dir.path()).await.unwrap();
        assert!(store.is_empty());

        let mut a = sample();
        a.id = "a".into();
        let mut b = sample();
        b.id = "b".into();
        store.record_received(&a).await.unwrap();
        store.record_received(&b).await.unwrap();
        store.record_forwarded("a").await.unwrap();

        let reopened = Store::open(dir.path()).await.unwrap();
        assert_eq!(reopened.len(), 2);
        assert_eq!(reopened.get("a"), Some(Entry { forwarded: true }));
        assert_eq!(reopened.get("b"), Some(Entry { forwarded: false }));
        assert_eq!(reopened.get("c"), None);

        let adif = std::fs::read_to_string(dir.path().join("log.adi")).unwrap();
        assert!(adif.starts_with("Generated by speech-to-qso-server\n"));
        assert_eq!(adif.matches("<EOH>").count(), 1);
        assert_eq!(adif.matches("<EOR>").count(), 2);
    }
}
